site_name: Веб-программирование. Левчук Софья. K3341
site_description: Отчёты по лабораторным работам
theme:
  name: material
  language: ru
  palette:
    primary: green
    accent: light green

nav:
  - Главная: index.md
  - ЛР1:
      - Отчёт: lr1/report.md
  - ЛР2:
      - Отчёт: lr2/report.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - tables